---
title: "Extracting_Posterior_Predictions"
author: "Jennifer McHenry"
date: "2023-12-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidybayes)
library(brms)
library(marginaleffects)
library(ggokabeito)
library(modelr)
library(bayestestR)
library(ggplot2)

theme_clean <- function() {
  theme_minimal(base_family = "News Cycle") +
    theme(panel.grid.minor = element_blank(),
          plot.title = element_text(face = "bold"),
          axis.title = element_text(face = "bold"),
          strip.text = element_text(face = "bold", size = rel(1), hjust = 0),
          strip.background = element_rect(fill = "grey80", color = NA),
          legend.title = element_text(face = "bold"))
}


theme_publish <- function(base_size = 12, base_family = "",
                          base_line_size = 0.25, ...) {
  half_line <- base_size / 2
  small_rel <- 0.8
  small_size <- small_rel * base_size
  
  # TODO: replace size with linewidth in `element_rect()`
  theme_bw(base_size = base_size, base_family = base_family, ...) %+replace%
    theme(
      rect = element_rect(fill = "transparent", colour = NA, color = NA,
                          size = 0, linetype = 0),
      text = element_text(family = base_family, face = "plain",
                          colour = "black", size = base_size, hjust = 0.5,
                          vjust = 0.5, angle = 0, lineheight = 0.9,
                          margin = ggplot2::margin(), debug = F),
      
      axis.text = element_text(size = small_size),
      axis.text.x = element_text(margin = ggplot2::margin(t = small_size/4),
                                 vjust = 1),
      axis.text.y = element_text(margin = ggplot2::margin(r = small_size/4), 
                                 hjust = 1),
      axis.title.x = element_text(margin = ggplot2::margin(t = small_size,
                                                           b = small_size)),
      axis.title.y = element_text(angle = 90,
                                  margin = ggplot2::margin(r = small_size,
                                                           l = small_size/4)),
      axis.ticks = element_line(colour = "black", size = base_line_size),
      axis.ticks.length = unit(0.25, 'lines'),
      
      axis.line = element_line(colour = "black", size = base_line_size),
      axis.line.x = element_line(colour = "black", size = base_line_size), 
      axis.line.y = element_line(colour = "black", size = base_line_size), 
      
      legend.spacing = unit(base_size/4, "pt"),
      legend.key = element_blank(),
      legend.key.size = unit(1 * base_size, "pt"),
      legend.key.width = unit(1.5 * base_size, 'pt'),
      legend.text = element_text(size = rel(small_rel)),
      legend.title = element_text(size = rel(small_rel), face = 'bold'),
      legend.position = 'bottom',
      legend.box = 'horizontal',
      
      panel.spacing = unit(1, "lines"),
      panel.background = element_blank(),
      panel.border = element_blank(), 
      # panel.grid.major = element_blank(),
      # panel.grid.minor = element_blank(),
      # 
      strip.text = element_text(size = base_size),
      strip.background = element_rect(fill = NA, colour = "black",
                                      size = 0.125),
      strip.text.x = element_text(face = 'bold', hjust = 0,
                                  margin = ggplot2::margin(b = small_size/2,
                                                           t = small_size/4)),
      strip.text.y = element_text(angle = -90, face = 'bold',
                                  margin = ggplot2::margin(l = small_size/2,
                                                           r = small_size/4)),
      
      plot.margin = unit(c(5,5,0,0), "pt"),
      plot.background = element_blank(),
      plot.title = element_text(face = "bold", size = 1.2 * base_size, 
                                margin = ggplot2::margin(b = half_line),
                                hjust = 0)
    )
}
```


# Loading the final BRMs for predicting the per-area carbon stock and production rates of kelp species 
```{r}
MP_stock<-readRDS("Final_Models//Mpy_stock_final.rds")
MP_prod<-readRDS("Final_Models/Mpy_prod_final.rds")
# 
NL_stock<-readRDS("Final_Models/Nleu_stock_final.rds")
NL_prod<-readRDS("Final_Models/Nleu_prod_final.rds")
# 
CC_stock<-readRDS("Final_Models/Cco_stock_final.rds")
CC_prod<-readRDS("Final_Models/Cco_prod_final.rds")
# 
AC_stock<-readRDS("Final_Models/Acl_stock_final.rds")
AC_prod<-readRDS("Final_Models/Acl_prod_final.rds")
# 
LDNI_stock<-readRDS("Final_Models/Ldi_Hni_stock_final.rds")
LDNI_prod<-readRDS("Final_Models/Ldi_Hni_prod_final.rds")
# 
LS_stock<-readRDS("Final_Models/Lso_stock_final.rds")
LS_prod<-readRDS("Final_Models/Lso_prod_final.rds")
# 
PC_stock<-readRDS("Final_Models/Pca_stock_final.rds")
PC_prod<-readRDS("Final_Models/Pcal_prod_final.rds")

PG_stock<-readRDS("Final_Models/Pga_stock_final.rds")
PG_prod<-readRDS("Final_Models/Pga_prod_final.rds")
# 
SL_stock<-readRDS("Final_Models/Sla_stock_final.rds")
SL_prod<-readRDS("Final_Models/Sla_prod_final.rds")
# 
```


# making dataframes representing the range of conditions that could be found in Canada
```{r}

#Making new prediction datasets
# C stocks
#M pyrifera
#checking how I should specific the sd portion.
summary(MP_stock$data$sd)

Mpyr_stock_test_df<-MP_stock$data%>%
  data_grid(sd=seq(0,2,1))%>%
  mutate(ocean=c("Pacific"))

#epreds
Mpyr.stock.epred <- MP_stock %>%
  epred_draws(newdata = Mpyr_stock_test_df,
              re_formula = NA)

Mpyr.stock.epred$taxa <-c("Macrocystis pyrifera")

# N leutkeana
#checking how I should specific the sd portion.
summary(NL_stock$data$sd)

Nleu_stock_test_df<-as.data.frame(NL_stock$data)%>%
  data_grid(sd=seq(0,6,1),ocean_temperature=seq(8,12))%>%
  mutate(ocean=c("Pacific"))

#epreds
Nleu.stock.epred <- NL_stock %>%
  epred_draws(newdata = Nleu_stock_test_df,
              re_formula = NA)

Nleu.stock.epred$taxa <-c("Nereocystis leutkeana")


#A clathratum / N fimbriatum
#checking how I should specific the sd portion.
summary(AC_stock$data$sd)

Aclath_stock_test_df_Pacific <-as.data.frame(AC_stock$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,1,1),ocean_temperature=seq(8,12),ocean=c("Pacific"))

Aclath_stock_test_df_Arctic <-as.data.frame(AC_stock$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,1,1),ocean_temperature=seq(-2,4),ocean=c("Arctic"))

Aclath_stock_test_df_Atlantic <-as.data.frame(AC_stock$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,1,1),ocean_temperature=seq(0,20),ocean=c("Atlantic"))

Aclath_stock_test_df<-rbind(Aclath_stock_test_df_Pacific,Aclath_stock_test_df_Arctic,Aclath_stock_test_df_Atlantic)

#epreds
Acla.stock.epred <- AC_stock %>%
  epred_draws(newdata = Aclath_stock_test_df,
              re_formula = NA)

Acla.stock.epred$taxa <-c("A. clathratum / N. fimbriatum")

#C. costaria

#checking how I should specific the sd portion.
summary(CC_stock$data$sd)

Ccost_stock_test_df<-as.data.frame(CC_stock$data)%>%
  data_grid(sd=seq(0,1,1),ocean="Pacific")

#epreds
Ccost.stock.epred <- CC_stock %>%
  epred_draws(newdata = Ccost_stock_test_df,
              re_formula = NA)

Ccost.stock.epred$taxa <-c("Costaria costata")


#L. solidungula
summary(SL_stock$data$sd)

Lsol_stock_test_df<-as.data.frame(LS_stock$data)%>%
  data_grid(sd=seq(0,11,1))%>%
  mutate(ocean=c("Arctic"))

#epreds
Lsol.stock.epred <- LS_stock %>%
  epred_draws(newdata = Lsol_stock_test_df,
              re_formula = NA)

Lsol.stock.epred$taxa <-c("Laminaria solidungula")

#P. gardeneri
summary(PG_stock$data$sd)

Pgar_stock_test_df<-as.data.frame(PG_stock$data)%>%
  data_grid(sd=seq(0,1,1))%>%
  mutate(ocean=c("Pacific"))


#epreds
Pgar.stock.epred <- PG_stock %>%
  epred_draws(newdata = Pgar_stock_test_df,
              re_formula = NA)


Pgar.stock.epred$taxa <-c("Pleurophycus gardneri")

#P. californica
summary(PC_stock$data$sd)

Pcal_stock_test_df<-as.data.frame(PC_stock$data)%>%
  select(sd)%>%
  data_grid(sd=seq(0,2,1),ocean="Pacific")

#epreds
Pcal.stock.epred <- PC_stock %>%
  epred_draws(newdata = Pcal_stock_test_df,
              re_formula = NA)

Pcal.stock.epred$taxa <-c("Pterygophgora californica")

#L dig
summary(LDNI_stock$data$sd)

LdigHnig_stock_test_df_Pacific <-as.data.frame(LDNI_stock$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,7,1),ocean_temperature=seq(8,12),ocean=c("Pacific"))

LdigHnig_stock_test_df_Arctic <-as.data.frame(LDNI_stock$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,7,1),ocean_temperature=seq(-2,4),ocean=c("Arctic"))


LdigHnig_stock_test_df_Atlantic <-as.data.frame(LDNI_stock$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,7,1),ocean_temperature=seq(0,20),ocean=c("Atlantic"))

LdigHnig_stock_test_df<-rbind(LdigHnig_stock_test_df_Pacific,LdigHnig_stock_test_df_Arctic,LdigHnig_stock_test_df_Atlantic)

#epreds
LdigHnig.stock.epred <- LDNI_stock %>%
  epred_draws(newdata = LdigHnig_stock_test_df,
              re_formula = NA)

LdigHnig.stock.epred$taxa <-c("L. digitata / H. nigripes")


#S Latissima
summary(SL_stock$data$sd)

Slat_stock_test_df_Pacific <-as.data.frame(SL_stock$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,11,1),ocean_temperature=seq(8,12),ocean=c("Pacific"))

Slat_stock_test_df_Arctic <-as.data.frame(SL_stock$data)%>%
  select(sd,ocean_temperature,ocean)%>%
  data_grid(sd=seq(0,11,1),ocean_temperature=seq(-2,4),ocean=c("Arctic"))

Slat_stock_test_df_Atlantic <-as.data.frame(SL_stock$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,11,1),ocean_temperature=seq(0,20),ocean=c("Atlantic"))

Slat_stock_test_df<-rbind(Slat_stock_test_df_Pacific,Slat_stock_test_df_Arctic,Slat_stock_test_df_Atlantic)

#epreds
Slat.stock.epred <- SL_stock %>%
  epred_draws(newdata = Slat_stock_test_df,
              re_formula = NA)

Slat.stock.epred$taxa <-c("Saccharina latissima")

All.stock.epred<-rbind(Mpyr.stock.epred,
                       Nleu.stock.epred,
                       Acla.stock.epred,
                       Ccost.stock.epred,
                       Lsol.stock.epred,
                       Pcal.stock.epred,
                       Pgar.stock.epred,
                       LdigHnig.stock.epred,
                       Slat.stock.epred)


All.stock.epred.summarized<-All.stock.epred %>%
  ungroup()%>%
  group_by(taxa,ocean)%>%
  summarize(across(.epred, lst(mean,bayestestR::ci), .names = "{.fn}"))%>%
  dplyr::mutate(ocean=factor(ocean,levels=c("Pacific","Arctic","Atlantic")))


#Making new prediction datasets
# C prod

#M pyrifera
summary(MP_prod$data$sd)

Mpyr_prod_test_df<-as.data.frame(MP_prod$data)%>%
  data_grid(sd=seq(0,6,1))%>%
  mutate(ocean=c("Pacific"))

#epreds
Mpyr.prod.epred <- MP_prod %>%
  epred_draws(newdata = Mpyr_prod_test_df,
              re_formula = NA)

Mpyr.prod.epred$taxa <-c("Macrocystis pyrifera")

# N leutkeana
summary(NL_prod$data$sd)

Nleu_prod_test_df<-as.data.frame(NL_prod$data)%>%
  data_grid(sd=seq(0,6,1), ocean_temperature=seq(8,12,1))%>%
  mutate(ocean=c("Pacific"))

#epreds
Nleu.prod.epred <- NL_prod %>%
  epred_draws(newdata = Nleu_prod_test_df,
              re_formula = NA)

Nleu.prod.epred$taxa <-c("Nereocystis leutkeana")

#A clathratum / N fimbriatum
#checking how I should specific the sd portion.
summary(AC_prod$data$sd)

Aclath_prod_test_df_Pacific <-as.data.frame(AC_prod$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,1,1),ocean_temperature=seq(8,12),ocean=c("Pacific"))

Aclath_prod_test_df_Arctic <-as.data.frame(AC_prod$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,1,1),ocean_temperature=seq(-2,4),ocean=c("Arctic"))

Aclath_prod_test_df_Atlantic <-as.data.frame(AC_prod$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,1,1),ocean_temperature=seq(0,20),ocean=c("Atlantic"))

Aclath_prod_test_df<-rbind(Aclath_prod_test_df_Pacific,Aclath_prod_test_df_Arctic,Aclath_prod_test_df_Atlantic)

#epreds
Acla.prod.epred <- AC_prod %>%
  epred_draws(newdata = Aclath_prod_test_df,
              re_formula = NA)

Acla.prod.epred$taxa <-c("A. clathratum / N. fimbriatum")

#C. costaria
summary(CC_prod$data$sd)

Ccost_prod_test_df<-as.data.frame(CC_prod$data)%>%
  data_grid(sd=seq(0,1,1))%>%
  mutate(ocean=c("Pacific"))

#epreds
Ccost.prod.epred <- CC_prod %>%
  epred_draws(newdata = Ccost_prod_test_df,
              re_formula = NA)

Ccost.prod.epred$taxa <-c("Costaria costata")


#L. solidungula
summary(LS_prod$data$sd)

Lsol_prod_test_df<-as.data.frame(LS_prod$data)%>%
  data_grid(sd=seq(0,1,1))%>%
  mutate(ocean=c("Arctic"))


#epreds
Lsol.prod.epred <- LS_prod %>%
  epred_draws(newdata = Lsol_prod_test_df,
              re_formula = NA)

Lsol.prod.epred$taxa <-c("Laminaria solidungula")

#P. gardeneri
Pgar_prod_test_df<-as.data.frame(PG_prod$data)%>%
  data_grid(sd=seq(0,1,1))%>%
  mutate(ocean=c("Pacific"))

#epreds
Pgar.prod.epred <- PG_prod %>%
  epred_draws(newdata = Pgar_prod_test_df,
              re_formula = NA)


Pgar.prod.epred$taxa <-c("Pleurophycus gardneri")

#P. californica
Pcal_prod_test_df<-as.data.frame(PC_prod$data)%>%
  data_grid(sd=seq(0,1,1))%>%
  mutate(ocean=c("Pacific"))

#epreds
Pcal.prod.epred <- PC_prod %>%
  epred_draws(newdata = Pcal_prod_test_df,
              re_formula = NA)

Pcal.prod.epred$taxa <-c("Pterygophora californica")

#L dig

summary(LDNI_prod$data$sd)

LdigHnig_prod_test_df_Pacific <-as.data.frame(LDNI_prod$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,2,1),ocean_temperature=seq(8,12),ocean=c("Pacific"))
# 
# LdigHnig_prod_test_df_Arctic <-as.data.frame(LDNI_prod$data)%>%
#   select(sd,ocean_temperature)%>%
#   data_grid(sd=seq(0,2,1),ocean_temperature=seq(-2,4),ocean=c("Arctic"))

LdigHnig_prod_test_df_Atlantic <-as.data.frame(LDNI_prod$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,2,1),ocean_temperature=seq(0,20),ocean=c("Atlantic"))


LdigHnig_prod_test_df<-rbind(LdigHnig_prod_test_df_Pacific,LdigHnig_prod_test_df_Atlantic)

#epreds
LdigHnig.prod.epred <- LDNI_prod %>%
  epred_draws(newdata = LdigHnig_prod_test_df,
              re_formula = NA)

LdigHnig.prod.epred$taxa <-c("L. digitata / H. nigripes")


#S Latissima
summary(SL_prod$data$sd)

Slat_prod_test_df_Pacific <-as.data.frame(SL_prod$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,7,1),ocean_temperature=seq(8,12),ocean=c("Pacific"))

Slat_prod_test_df_Arctic <-as.data.frame(SL_prod$data)%>%
  select(sd,ocean_temperature,ocean)%>%
  data_grid(sd=seq(0,7,1),ocean_temperature=seq(-2,4),ocean=c("Arctic"))

Slat_prod_test_df_Atlantic <-as.data.frame(SL_prod$data)%>%
  select(sd,ocean_temperature)%>%
  data_grid(sd=seq(0,7,1),ocean_temperature=seq(0,20),ocean=c("Atlantic"))

Slat_prod_test_df<-rbind(Slat_prod_test_df_Pacific,Slat_prod_test_df_Arctic,Slat_prod_test_df_Atlantic)

#epreds
Slat.prod.epred <- SL_prod %>%
  epred_draws(newdata = Slat_prod_test_df,
              re_formula = NA)

Slat.prod.epred$taxa <-c("Saccharina latissima")


All.prod.epred<-rbind(Mpyr.prod.epred,
                       Nleu.prod.epred,
                       Acla.prod.epred,
                       Ccost.prod.epred,
                       Lsol.prod.epred,
                       Pcal.prod.epred,
                       Pgar.prod.epred,
                       LdigHnig.prod.epred,
                       Slat.prod.epred)

All.prod.epred.summarized<-All.prod.epred %>%
  ungroup()%>%
  group_by(taxa,ocean)%>%
  summarize(across(.epred, lst(mean,median,ci), .names = "{.fn}"))%>%      dplyr::mutate(ocean=factor(ocean,levels=c("Pacific","Arctic","Atlantic")))
# write.csv(All.prod.epred.summarized,file="outputs/C_Prod_Posterior_means_CIs.csv")
# 
# write.csv(All.stock.epred.summarized,file="outputs/C_Stock_Posterior_means_CIs.csv")

```


```{r}

p1<-ggplot(All.stock.epred, aes(x = .epred,y=reorder(taxa,.epred),color=ocean)) +
  # stat_halfeye(position="dodge")+
  tidybayes::stat_pointinterval(position = "dodge",.width=c(0.89))+
  labs(x = "C Stock (Mg C Ha-1)", y = NULL)+
  ggtitle("a.") +
  theme_clean() + theme_publish(base_size = 12)+
  coord_cartesian(xlim=c(0,4)) + scale_colour_manual(values=c("#0070C0","#00B251","#7030A0"))


p2<-All.prod.epred%>%
  mutate(taxa=factor(taxa,levels=c("Pleurophycus gardneri","Costaria costata","A. clathratum / N. fimbriatum","Laminaria solidungula","L. digitata / H. nigripes","Pterygophora californica","Saccharina latissima","Macrocystis pyrifera","Nereocystis leutkeana")))%>%
  ggplot(aes(x = .epred,y=taxa,color=ocean)) +
  # stat_halfeye(position = "dodge")+
stat_pointinterval(aes(x = .epred,y=taxa,color=ocean), position = "dodge",point_interval =  "mean_qi", .width=c(0.89))+
  labs(x = " C Prod Rate (Mg C Ha-1 Yr-1)", y = NULL)+
  ggtitle("b. ") +
  theme_clean() + theme_publish(base_size = 12)+
  coord_cartesian(xlim=c(0, 20)) + scale_colour_manual(values=c("#0070C0","#00B251","#7030A0"))


pdf("plots/Figure4.pdf",height=4,width=10)
p1 + p2 
dev.off()


pane_b <-p1 + p2 + plot_annotation("Per-area carbon stock and production capacity of Canada's Kelps")

```


## Percentage of conditional difference
```{r}

C_stock_posterior_mean_comparisons_input_df <- All.stock.epred%>%
  ungroup()%>%
  select(taxa,ocean,.epred)%>%
  mutate(species = paste(taxa,"-",ocean))%>%
  select(species,.epred)

C_prod_posterior_mean_comparisons_input_df <- All.prod.epred%>%
  ungroup()%>%
  select(taxa,ocean,.epred)%>%
  mutate(species = paste(taxa,"-",ocean))%>%
  select(species,.epred)


compare_posterior_distributions <- function(data_df, num_bootstrap = 1000) {
  # Extract unique species names
  species_list <- unique(data_df$species)
  
  # Create all possible combinations of species
  species_combinations <- expand.grid(species_list, species_list)
  species_combinations <- species_combinations[species_combinations$Var1 != species_combinations$Var2, ]
  
  # Create an empty dataframe to store the results
  percent_diff_df <- data.frame()
  
  # Bootstrap method to compare samples of different lengths
  bootstrap_compare <- function(sample1, sample2, n) {
    mean_diffs <- replicate(n, {
      idx <- sample(length(sample1), length(sample2), replace = TRUE)
      mean(sample1[idx] > sample2)
    })
    return(mean_diffs)
  }
  
  # Calculate percent difference between all pairs of species
  for (i in 1:nrow(species_combinations)) {
    species1 <- species_combinations$Var1[i]
    species2 <- species_combinations$Var2[i]
    samples1 <- unlist(data_df[data_df$species == species1, -1])
    samples2 <- unlist(data_df[data_df$species == species2, -1])
    
    percent_diff <- mean(bootstrap_compare(samples1, samples2, num_bootstrap)) * 100
    
    # Add the result to the dataframe
    result <- data.frame(Species1 = species1, Species2 = species2, Percent_Difference = percent_diff)
    percent_diff_df <- rbind(percent_diff_df, result)
  }
  
  return(percent_diff_df)
}


C_stock_posterior_mean_comparisons_output_df <-compare_posterior_distributions(C_stock_posterior_mean_comparisons_input_df, 100)


C_stock_posterior_pairwise_matrix <-C_stock_posterior_mean_comparisons_output_df%>%
  pivot_wider(Species1,names_from = Species2,values_from =Percent_Difference)


write.csv(C_stock_posterior_pairwise_matrix, file = "outputs/C_stock_posterior_mean_comparisons_output_df.csv")

C_prod_posterior_mean_comparisons_output_df <-compare_posterior_distributions(C_prod_posterior_mean_comparisons_input_df, 100)


C_prod_posterior_pairwise_matrix <-C_prod_posterior_mean_comparisons_output_df%>%
  pivot_wider(Species1,names_from = Species2,values_from =Percent_Difference)

write.csv(C_prod_posterior_pairwise_matrix, file = "outputs/C_prod_posterior_mean_comparisons_output_df.csv")

```

Making a table for presentation of pairwise comparisons 
```{r}
library(spaa)
C_stock_posterior_pairwise_matrix<-read.csv("outputs/C_stock_posterior_mean_comparisons_output_df.csv")


C_prod_posterior_pairwise_matrix<-read.csv("outputs/C_prod_posterior_mean_comparisons_output_df.csv")

```

