---
title: "Estimating Carbon Production Rates Associated with Canadian Kelps using BRMs"
author: "Jennifer McHenry"
date: '2023-02-23'
output:
  html_document: default
  pdf_document: default
---


```{r,include=FALSE}
# Setting up Rstan


# remove.packages(c("rstan", "StanHeaders"))
# if (file.exists(".RData")) file.remove(".RData")
# # #

# install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))

# update.packages("rstan")
library(StanHeaders)
library(rstan)
library(collapse)
# install.packages("collapse")

# example(stan_model, package = "rstan", run.dontrun = TRUE)

# rstan_options(auto_write=TRUE)
# install.packages("brms", dependencies = TRUE)
```

```{r,include=FALSE}
# Load required libraries
library(brms)         # Bayesian modeling through Stan
library(tidyverse)    # ggplot, dplyr, %>%, and friends
library(tidybayes)    # Manipulate Stan objects in a tidy way
library(broom)        # Convert model objects to data frames
library(broom.mixed)  # Convert brms model objects to data frames
library(emmeans)      # Calculate marginal effects in even fancier ways
library(patchwork)    # Combine ggplot objects
library(ggokabeito)   # Neat accessible color palette
library(gghalves)     # Special half geoms
library(ggbeeswarm)   # Special distribution-shaped point jittering
library(HDInterval)
library(marginaleffects)
library(performance)
library(loo)
library(bayesplot)
library(bayestestR)
library(rstanarm)

theme_clean <- function() {
  theme_minimal(base_family = "News Cycle") +
    theme(panel.grid.minor = element_blank(),
          plot.title = element_text(face = "bold"),
          axis.title = element_text(face = "bold"),
          strip.text = element_text(face = "bold", size = rel(1), hjust = 0),
          strip.background = element_rect(fill = "grey80", color = NA),
          legend.title = element_text(face = "bold"))
}


theme_publish <- function(base_size = 12, base_family = "",
                          base_line_size = 0.25, ...) {
  half_line <- base_size / 2
  small_rel <- 0.8
  small_size <- small_rel * base_size
  
  # TODO: replace size with linewidth in `element_rect()`
  theme_bw(base_size = base_size, base_family = base_family, ...) %+replace%
    theme(
      rect = element_rect(fill = "transparent", colour = NA, color = NA,
                          size = 0, linetype = 0),
      text = element_text(family = base_family, face = "plain",
                          colour = "black", size = base_size, hjust = 0.5,
                          vjust = 0.5, angle = 0, lineheight = 0.9,
                          margin = ggplot2::margin(), debug = F),
      
      axis.text = element_text(size = small_size),
      axis.text.x = element_text(margin = ggplot2::margin(t = small_size/4),
                                 vjust = 1),
      axis.text.y = element_text(margin = ggplot2::margin(r = small_size/4), 
                                 hjust = 1),
      axis.title.x = element_text(margin = ggplot2::margin(t = small_size,
                                                           b = small_size)),
      axis.title.y = element_text(angle = 90,
                                  margin = ggplot2::margin(r = small_size,
                                                           l = small_size/4)),
      axis.ticks = element_line(colour = "black", size = base_line_size),
      axis.ticks.length = unit(0.25, 'lines'),
      
      axis.line = element_line(colour = "black", size = base_line_size),
      axis.line.x = element_line(colour = "black", size = base_line_size), 
      axis.line.y = element_line(colour = "black", size = base_line_size), 
      
      legend.spacing = unit(base_size/4, "pt"),
      legend.key = element_blank(),
      legend.key.size = unit(1 * base_size, "pt"),
      legend.key.width = unit(1.5 * base_size, 'pt'),
      legend.text = element_text(size = rel(small_rel)),
      legend.title = element_text(size = rel(small_rel), face = 'bold'),
      legend.position = 'bottom',
      legend.box = 'horizontal',
      
      panel.spacing = unit(1, "lines"),
      panel.background = element_blank(),
      panel.border = element_blank(), 
      # panel.grid.major = element_blank(),
      # panel.grid.minor = element_blank(),
      # 
      strip.text = element_text(size = base_size),
      strip.background = element_rect(fill = NA, colour = "black",
                                      size = 0.125),
      strip.text.x = element_text(face = 'bold', hjust = 0,
                                  margin = ggplot2::margin(b = small_size/2,
                                                           t = small_size/4)),
      strip.text.y = element_text(angle = -90, face = 'bold',
                                  margin = ggplot2::margin(l = small_size/2,
                                                           r = small_size/4)),
      
      plot.margin = unit(c(5,5,0,0), "pt"),
      plot.background = element_blank(),
      plot.title = element_text(face = "bold", size = 1.2 * base_size, 
                                margin = ggplot2::margin(b = half_line),
                                hjust = 0)
    )
}
```

# Bayesian Model Sources
```{r}
# https://vasishth.github.io/bayescogsci/book/ch-remame.html

# https://www.rdocumentation.org/packages/brms/versions/0.9.1/topics/brm

# https://vincentarelbundock.github.io/marginaleffects/articles/brms.html

# https://paul-buerkner.github.io/brms/reference/posterior_summary.html

# https://www.andrewheiss.com/blog/2021/11/10/ame-bayes-re-guide/#different-kinds-of-average-predictions-with-multilevel-models
```


# Data 
```{r,include=FALSE}
C_Production_Collated_DF<-read.csv("final_collated_data/collated_kelp_C_NPP_production_singlemodel_df.csv")

```

```{r,include=FALSE}

C_prod_rate_model_data <- data.frame(
  ocean= C_Production_Collated_DF$Coast, #Arctic, Atlantic, Pacific
  canopy_type = C_Production_Collated_DF$Canopy_Type,# surface vs subsurface
  site = C_Production_Collated_DF$Site,  # Site identifier
  taxa = C_Production_Collated_DF$Taxa, #species
  year = paste(C_Production_Collated_DF$Start_year,C_Production_Collated_DF$End_year,sep="_"),
  latitude = C_Production_Collated_DF$Latitude_dd,
  ocean_temperature = C_Production_Collated_DF$Mean_SST_BioOracle,
  PAR = C_Production_Collated_DF$Mean_PAR_BioOracle,
  effect = C_Production_Collated_DF$Avg_Production_MgC_ha_y1,  # Site or study level mean
  sd = C_Production_Collated_DF$stdev_Production_MgC_ha_y1,
  source = C_Production_Collated_DF$Reference)%>% # Site or study level sd on the mean 
  mutate(observation_id = 1:n(), 
         # sd=ifelse(sd==0,NA,sd))
          sd=ifelse(is.na(sd)==TRUE,0,sd))%>%
    mutate(taxa=ifelse(taxa=="Hedophyllum nigripes" | taxa=="Laminaria digitata","L. digitata / H. nigripes",taxa))
    # filter(month=="June")


#splitting the data by species
C_prod_model_data_sppsplit <-C_prod_rate_model_data%>%
  group_by(taxa)

C_prod_model_data_sppsplit<-group_split(C_prod_model_data_sppsplit)

```

```{r,include=FALSE}
#Carbon Prod DF
str(C_prod_model_data_sppsplit)

```

# Summary Stats
```{r,echo=FALSE}
# By Species
C_prod_rate_model_data%>%
    # group_by(ocean)%>%
    # group_by(taxa)%>%
  dplyr::summarise(mean=mean(effect),max=max(effect),upper=quantile(effect,probs= 0.75),lower=quantile(effect, probs= 0.25), min=min(effect), sd=sd(effect), n=length(effect), se=sd/sqrt(n),cv=sd/mean*100)%>%
  arrange(-mean)

```


# Setting up the priors
```{r}
#for intercept only models
priors_IO<- c(prior(student_t(3,0,9), class = Intercept),
             prior(student_t(3,0,9), class = sigma))


#for mixed effects models
priors_FE<- c(prior(student_t(3,0,9), class = Intercept),
              prior(student_t(3,0,9),class=b),
              prior(student_t(3,0,9), class = sigma))


```

# C PRODUCTION RATE MODELS - 

## Macrocystis pyrifera
```{r,results = FALSE}
Mpyr_C_prod_df <- C_prod_model_data_sppsplit[[5]]

Mpyr_C_prod_test_df<-Mpyr_C_prod_df%>%
  # select(ocean,sd,ocean_temperature)%>%
  # mutate(sd=as.integer(sd),ocean_temperature=as.integer(ocean_temperature))
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd))


Mpyr_C_prod_test_df<-unique(Mpyr_C_prod_test_df)
Mpyr_C_prod_test_df$site <- NA
Mpyr_C_prod_test_df$year <- NA

Mpyr.prod.1 <- brm(data = Mpyr_C_prod_df,
                   family= gaussian,
                  formula = effect | resp_se(`sd`) ~ ocean_temperature + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

Mpyr.prod.2 <- brm(data = Mpyr_C_prod_df,
                   family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~ (1 |year) +(1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

```

```{r}
loo(Mpyr.prod.1,Mpyr.prod.2)

Mpyr.prod.final <- Mpyr.prod.2

##save model output object
saveRDS(Mpyr.prod.final, file="final_brms/Mpy_prod_final.rds")

performance::r2(Mpyr.prod.final)

# conditional_effects(Mpyr.prod.final)

summary(Mpyr.prod.final)

plot(Mpyr.prod.final, ask = FALSE)

# Comparing priors to posteriors
Mpyr_priors <- prior_draws(Mpyr.prod.final)
Mpyr_post<- as.data.frame(Mpyr.prod.final)

ggplot() +
  geom_density(data = Mpyr_priors, aes(x = Intercept)) +
  geom_density(data = Mpyr_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(Mpyr.prod.final)

#grand means
Mpyr.epred <- Mpyr.prod.final %>%
  epred_draws(newdata = Mpyr_C_prod_test_df,
              re_formula = NA)

avg_predictions(model = Mpyr.prod.final,by="ocean",newdata=Mpyr_C_prod_df,conf_level = 0.95)


ggplot(Mpyr.epred, aes(x = .epred,y=ocean,fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "Macrocystis pyrifera - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")

# Bayes tests

# #describing the full posterior distribution
Mpyr_estiamtes <- as.data.frame(describe_posterior(Mpyr.prod.final,centrality="mean"))
Mpyr_estiamtes$taxa <- c("Macrocystis pyrifera")

Mpyr_estiamtes

write.csv(Mpyr_estiamtes,file="outputs/Mpyr_C_prod_rate_estiamtes.csv")
```

## Nereocystis leutkeana
```{r,results = FALSE}
Nleu_C_prod_df <- C_prod_model_data_sppsplit[[6]]%>%
    filter(source!="Subsurface Datasets from Hakai (Margot Hessing-Lewis; Ondine Pontier; Luba Retinyk; Daniel Okamoto)")

  

Nleu_c_prod_test_df<-Nleu_C_prod_df%>%
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd)) 

Nleu_c_prod_test_df<-unique(Nleu_c_prod_test_df)
Nleu_c_prod_test_df$site <- NA
Nleu_c_prod_test_df$year <- NA

Nleu.prod.1 <- brm(data = Nleu_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~ ocean_temperature + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


Nleu.prod.2 <- brm(data = Nleu_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~ (1 |year) +(1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

```

```{r}
loo(Nleu.prod.1,Nleu.prod.2)

Nleu.prod.final <- Nleu.prod.1

##save model output object
saveRDS(Nleu.prod.final, file="final_brms/Nleu_prod_final.rds")

performance::r2(Nleu.prod.final)

summary(Nleu.prod.final)

conditional_effects(Nleu.prod.final)


plot(Nleu.prod.final, ask = FALSE)

# Comparing priors to posteriors
Nleu_priors <- prior_draws(Nleu.prod.final)
Nleu_post<- as.data.frame(Nleu.prod.final)

ggplot() +
  geom_density(data = Nleu_priors, aes(x = Intercept)) +
  geom_density(data = Nleu_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  # xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(Nleu.prod.final)


# grand mean predictions

#grand means
Nleu.epred <- Nleu.prod.final %>%
  epred_draws(newdata = Nleu_c_prod_test_df,
              re_formula = NA)

avg_predictions(model = Nleu.prod.final,by="ocean",newdata=Nleu_C_prod_df,conf_level = 0.95)

ggplot(Nleu.epred, aes(x = .epred,y=ocean, fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "Nereocystis leutkeana - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")

# Bayes tests

#describing the full posterior distribution
Nleu_estiamtes <- as.data.frame(describe_posterior(Nleu.prod.final,centrality="mean"))
Nleu_estiamtes$taxa <- c("Nereocystis leutkeana")

Nleu_estiamtes

write.csv(Nleu_estiamtes,file="outputs/Nleu_C_prod_rate_estiamtes.csv")


```

## Agarum clathratum / Neoagarum fimbriatum 
```{r,results = FALSE}
Aclath_C_prod_df <- C_prod_model_data_sppsplit[[1]]
  # filter(is.na(latitude)==FALSE)

Alcath_c_prod_test_df<-Aclath_C_prod_df%>%
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd))

Alcath_c_prod_test_df<-unique(Alcath_c_prod_test_df)
Alcath_c_prod_test_df$site <- NA
Alcath_c_prod_test_df$year <- NA

# 
Aclath.prod.1 <- brm(data = Aclath_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean_temperature + ocean + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


# 
Aclath.prod.2 <- brm(data = Aclath_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean_temperature + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


Aclath.prod.3 <- brm(data = Aclath_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                   sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


  
Aclath.prod.4<-brm(data = Aclath_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  (1 |year) +(1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

```

```{r}
loo(Aclath.prod.1,Aclath.prod.2,Aclath.prod.3,Aclath.prod.4)

Aclah.prod.final <- Aclath.prod.2

##save model output object
saveRDS(Aclah.prod.final, file="final_brms/Acl_prod_final.rds")

performance::r2(Aclah.prod.final)

summary(Aclah.prod.final)

# conditional_effects(Aclah.prod.final)

plot(Aclah.prod.final, ask = FALSE)

# Comparing priors to posteriors
Aclath_priors <- prior_draws(Aclah.prod.final)
Aclath_post<- as.data.frame(Aclah.prod.final)

ggplot() +
  geom_density(data = Aclath_priors, aes(x = Intercept)) +
  geom_density(data = Aclath_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(Aclah.prod.final)


# grand mean predictions

#grand means
Aclath.epred <- Aclah.prod.final %>%
  epred_draws(newdata = Alcath_c_prod_test_df,
              re_formula = NA)

avg_predictions(model = Aclah.prod.final,by="ocean",newdata=Aclath_C_prod_df,conf_level = 0.95)

avg_predictions(model = Aclah.prod.final,newdata=Aclath_C_prod_df,conf_level = 0.95)


Aclah.prod.final %>% 
  emmeans(~ 1,
          # at = list(ocean = "Pacific"),
          epred = TRUE, re_formula = NA) %>% 
  # contrast(method = "revpairwise") %>% 
  gather_emmeans_draws()%>%
  mean_hdci()


ggplot(Aclath.epred, aes(x = .epred,y=ocean,fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "A. clathratum / N. fimbriatum - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")


# Bayes tests

#describing the full posterior distribution
Aclath_estiamtes <- as.data.frame(describe_posterior(Aclah.prod.final,centrality="mean"))
Aclath_estiamtes$taxa <- c("A. clathratum / N; fimbriatum")

Aclath_estiamtes

avg_predictions(model = Aclah.prod.final,by="ocean",newdata=Aclath_C_prod_df)

write.csv(Aclath_estiamtes,file="outputs/Aclath_C_prod_rate_estiamtes.csv")

```


## Costaria costata
```{r,results = FALSE}
Ccost_C_prod_df <- C_prod_model_data_sppsplit[[2]]
  # filter(is.na(latitude)==FALSE)

Ccost_c_prod_test_df<-Ccost_C_prod_df%>%
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd))

Ccost_c_prod_test_df<-unique(Ccost_c_prod_test_df)
Ccost_c_prod_test_df$site <- NA
Ccost_c_prod_test_df$year <- NA

# 
Ccost.prod.1 <- brm(data = Ccost_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean_temperature + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

# 
Ccost.prod.2 <- brm(data = Ccost_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  (1 |year) +(1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

```

```{r}
loo(Ccost.prod.1,Ccost.prod.2)

Ccost.prod.final <- Ccost.prod.2

##save model output object
saveRDS(Ccost.prod.final, file="final_brms/Cco_prod_final.rds")

performance::r2(Ccost.prod.final)

summary(Ccost.prod.final)
# 
# conditional_effects(Ccost.prod.final)
# avg_predictions(model = Ccost.prod.final,by="ocean",newdata = Ccost_C_prod_df)

plot(Ccost.prod.final, ask = FALSE)

# Comparing priors to posteriors
Ccost_priors <- prior_draws(Ccost.prod.final)
Ccost_post<- as.data.frame(Ccost.prod.final)

ggplot() +
  geom_density(data = Ccost_priors, aes(x = Intercept)) +
  geom_density(data = Ccost_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(Ccost.prod.final)


# grand mean predictions

#grand means
Ccost.epred <- Ccost.prod.final %>%
  epred_draws(newdata = Ccost_c_prod_test_df,
              re_formula = NA)

avg_predictions(model = Ccost.prod.final,by="ocean",newdata=Ccost_C_prod_df,conf_level = 0.95)

ggplot(Ccost.epred, aes(x = .epred,y=ocean,fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "Costaria costata - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")


# Bayes tests

#describing the full posterior distribution
Ccost_estiamtes <- as.data.frame(describe_posterior(Ccost.prod.final,centrality="mean"))
Ccost_estiamtes$taxa <- c("Costaria costata")

Ccost_estiamtes

write.csv(Ccost_estiamtes,file = "outputs/Ccost_C_prod_rate_estiamtes.csv")

```

## Laminaria digitata / Hedophyllum nigripes
```{r,results = FALSE}
LdigHnig_C_prod_df <- C_prod_model_data_sppsplit[[3]]

LdigHnig_c_prod_test_df<-LdigHnig_C_prod_df%>%
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd))

LdigHnig_c_prod_test_df<-unique(LdigHnig_c_prod_test_df)
LdigHnig_c_prod_test_df$site <- NA
LdigHnig_c_prod_test_df$year <- NA


LdigHnig.prod.1 <- brm(data = LdigHnig_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean_temperature + ocean +  (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)



LdigHnig.prod.2 <- brm(data = LdigHnig_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean_temperature +  (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


LdigHnig.prod.3 <- brm(data = LdigHnig_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean +  (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                   sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)



LdigHnig.prod.4 <- brm(data = LdigHnig_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  (1 |year) +(1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

```

```{r}
loo(LdigHnig.prod.1,LdigHnig.prod.2,LdigHnig.prod.3,LdigHnig.prod.4)

LdigHnig.prod.final <- LdigHnig.prod.2

##save model output object
saveRDS(LdigHnig.prod.final, file="final_brms/Ldi_Hni_prod_final.rds")

performance::r2(LdigHnig.prod.final)

summary(LdigHnig.prod.final)
# 
conditional_effects(LdigHnig.prod.final)

plot(LdigHnig.prod.final, ask = FALSE)

# Comparing priors to posteriors
LdigHnig_priors <- prior_draws(LdigHnig.prod.final)
LdigHnig_post<- as.data.frame(LdigHnig.prod.final)

ggplot() +
  geom_density(data = LdigHnig_priors, aes(x = Intercept)) +
  geom_density(data = LdigHnig_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(LdigHnig.prod.final)


# grand mean predictions

#grand means
LdigHnig.epred <- LdigHnig.prod.final %>%
  epred_draws(newdata = LdigHnig_c_prod_test_df,
              re_formula = NA)


avg_predictions(model = LdigHnig.prod.final,by="ocean",newdata=LdigHnig_C_prod_df,conf_level = 0.95)

avg_predictions(model = LdigHnig.prod.final,newdata=LdigHnig_C_prod_df,conf_level = 0.95)


ggplot(LdigHnig.epred, aes(x = .epred,y=ocean,fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "L. digitata / H. nigripes - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")

#describing the full posterior distribution
LdigHnig_estiamtes <- as.data.frame(describe_posterior(LdigHnig.prod.final,centrality="mean"))
LdigHnig_estiamtes$taxa <- c("L. digitata / H. nigripes")

avg_predictions(model = LdigHnig.prod.final,by="ocean",newdata=LdigHnig_C_prod_df)

write.csv(LdigHnig_estiamtes,file = "outputs/LdigHnig_C_prod_rate_estiamtes.csv")

```


## Laminaria solidungula
```{r,results = FALSE}
Lsol_C_prod_df <- C_prod_model_data_sppsplit[[4]]

Lsol_c_prod_test_df<-Lsol_C_prod_df%>%
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd))

Lsol_c_prod_test_df<-unique(Lsol_c_prod_test_df)
Lsol_c_prod_test_df$site <- NA
Lsol_c_prod_test_df$year <- NA
# 
Lsol.prod.1  <- brm(data = Lsol_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean_temperature + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


Lsol.prod.2 <- brm(data = Lsol_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  (1 |year) +(1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

```

```{r}
loo(Lsol.prod.1,Lsol.prod.2)


Lsol.prod.final <-Lsol.prod.2

##save model output object
saveRDS(Lsol.prod.final, file="final_brms/Lso_prod_final.rds")

performance::r2(Lsol.prod.final)

summary(Lsol.prod.final)

plot(Lsol.prod.final, ask = FALSE)

# Comparing priors to posteriors
Lsol_priors <- prior_draws(Lsol.prod.final)
Lsol_post<- as.data.frame(Lsol.prod.final)

ggplot() +
  geom_density(data = Lsol_priors, aes(x = Intercept)) +
  geom_density(data = Lsol_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(Lsol.prod.final)


# grand mean predictions

#grand means
Lsol.epred <- Lsol.prod.final %>%
  epred_draws(newdata = Lsol_c_prod_test_df,
              re_formula = NA)

avg_predictions(model = Lsol.prod.final,by="ocean",newdata=Lsol_C_prod_df,conf_level = 0.95)


ggplot(Lsol.epred, aes(x = .epred,y=ocean,fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "Laminaria solidungula - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")

#describing the full posterior distribution
Lsol_estiamtes <- as.data.frame(describe_posterior(Lsol.prod.final,centrality="mean"))
Lsol_estiamtes$taxa <- c("Laminaria solidungula")

Lsol_estiamtes

write.csv(Lsol_estiamtes,file = "outputs/Lsol_C_prod_rate_estiamtes.csv")

```


## Pleurophycus gardneri
```{r,results = FALSE}
Pgar_C_prod_df <- C_prod_model_data_sppsplit[[7]]#

Pgar_c_prod_test_df<-Pgar_C_prod_df%>%
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd))

Pgar_c_prod_test_df<-unique(Pgar_c_prod_test_df)
Pgar_c_prod_test_df$site <- NA
Pgar_c_prod_test_df$year <- NA
# 
Pgar.prod.1 <- brm(data = Pgar_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~ ocean_temperature + (1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


Pgar.prod.2 <- brm(data = Pgar_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~ (1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

```

```{r}

loo(Pgar.prod.1,Pgar.prod.2)

Pgar.prod.final <- Pgar.prod.2

##save model output object
saveRDS(Pgar.prod.final, file="final_brms/Pga_prod_final.rds")

performance::r2(Pgar.prod.final)

summary(Pgar.prod.final)

plot(Pgar.prod.final, ask = FALSE)

# Comparing priors to posteriors
Pgar_priors <- prior_draws(Pgar.prod.final)
Pgar_post<- as.data.frame(Pgar.prod.final)

ggplot() +
  geom_density(data = Pgar_priors, aes(x = Intercept)) +
  geom_density(data = Pgar_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(Pgar.prod.final)


# grand mean predictions

#grand means
Pgar.epred <- Pgar.prod.final %>%
  epred_draws(newdata = Pgar_c_prod_test_df,
              re_formula = NA)

avg_predictions(model = Pgar.prod.final,by="ocean",newdata=Pgar_C_prod_df,conf_level = 0.95)

ggplot(Pgar.epred, aes(x = .epred,y=ocean,fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "Pleurophycus gardenari - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")

describing the full posterior distribution
Pgar_estiamtes <- as.data.frame(describe_posterior(Pgar.prod.final,centrality="mean"))
Pgar_estiamtes$taxa <- c("Pleurophycus gardenari")

Pgar_estiamtes

write.csv(Pgar_estiamtes,file = "outputs/Pgar_C_prod_rate_estiamtes.csv")

```


## Pterogophora californica
```{r,results = FALSE}
Pcal_C_prod_df <- C_prod_model_data_sppsplit[[8]]

Pcal_c_prod_test_df<-Pcal_C_prod_df%>%
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd))

Pcal_c_prod_test_df<-unique(Pcal_c_prod_test_df)
Pcal_c_prod_test_df$site <- NA
Pcal_c_prod_test_df$year <- NA


Pcal.prod.1 <- brm(data = Pcal_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~ 1,
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)
```

```{r}
Pcal.prod.final <- Pcal.prod.1
saveRDS(Pcal.prod.final, file="final_brms/Pcal_prod_final.rds")

performance::r2(Pcal.prod.final)

summary(Pcal.prod.final)

plot(Pcal.prod.final, ask = FALSE)

# Comparing priors to posteriors
Pcal_priors <- prior_draws(Pcal.prod.final)
Pcal_post<- as.data.frame(Pcal.prod.final)

ggplot() +
  geom_density(data = Pcal_priors, aes(x = Intercept)) +
  geom_density(data = Pcal_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(Pcal.prod.final)


# grand mean predictions

#grand means
Pcal.epred <- Pcal.prod.final %>%
  epred_draws(newdata = Pcal_c_prod_test_df,
              re_formula = NA)

avg_predictions(model = Pcal.prod.final,by="ocean",newdata=Pcal_C_prod_df,conf_level = 0.95)

ggplot(Pcal.epred, aes(x = .epred,y=ocean,fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "Pterogophora californica - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")

describing the full posterior distribution
Pcal_estiamtes <- as.data.frame(describe_posterior(Pcal.prod.final,centrality="mean"))
Pcal_estiamtes$taxa <- c("Pterogophora californica")

Pcal_estiamtes

write.csv(Pcal_estiamtes,file = "outputs/Pcal_C_prod_rate_estiamtes.csv")

```


## Saccharina latissima
```{r,results = FALSE}
Slat_C_prod_df <- C_prod_model_data_sppsplit[[9]]
  # filter(is.na(latitude)==FALSE)

Slat_c_prod_test_df<-Slat_C_prod_df%>%
  select(ocean,sd,ocean_temperature)%>%
  mutate(sd=as.integer(sd))

Slat_c_prod_test_df<-unique(Slat_c_prod_test_df)
Slat_c_prod_test_df$site <- NA
Slat_c_prod_test_df$year <- NA

# 
Slat.prod.1 <- brm(data = Slat_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean_temperature + ocean + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


Slat.prod.2 <- brm(data = Slat_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean_temperature + (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


Slat.prod.3 <- brm(data = Slat_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  ocean+ (1 |year) +(1 |site),
                  prior = priors_FE,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)


Slat.prod.4 <- brm(data = Slat_C_prod_df,
                  family= gaussian,
                  formula = effect | resp_se(`sd`,sigma = TRUE) ~  (1 |year) +(1 |site),
                  prior = priors_IO,
                  control = list(
                    adapt_delta = .99,
                    max_treedepth = 15),
                  sample_prior = TRUE,
                  iter=5000, warmup=2500, chains = 3)

```

```{r}
loo(Slat.prod.1,Slat.prod.2,Slat.prod.3,Slat.prod.4)

Slat.prod.final <- Slat.prod.1

#save model output object
saveRDS(Slat.prod.final, file="final_brms/Sla_prod_final.rds")

performance::r2(Slat.prod.final)

summary(Slat.prod.final)

conditional_effects(Slat.prod.final)

plot(Slat.prod.final, ask = FALSE)

# Comparing priors to posteriors
Slat_priors <- prior_draws(Slat.prod.final)
Slat_post<- as.data.frame(Slat.prod.final)

ggplot() +
  geom_density(data = Slat_priors, aes(x = Intercept)) +
  geom_density(data = Slat_post, aes(x = b_Intercept), color = "blue") +
  labs(title = "Prior Distribution vs. Posterior Distribution") +
  xlim(-30,  30) +
  theme_classic()

# Comparing prior predictive check plots - for model accuracy
pp_check(Slat.prod.final)


# grand mean predictions

#grand means
Slat.epred <- Slat.prod.final %>%
  epred_draws(newdata = Slat_c_prod_test_df,
              re_formula = NA)

avg_predictions(model = Slat.prod.final,by="ocean",newdata=Slat_C_prod_df,conf_level = 0.95)

ggplot(Slat.epred, aes(x = .epred,y=ocean,fill=ocean)) +
  stat_halfeye() +
  scale_fill_okabe_ito() +
  labs(x = "Predicted C Prod (Mg C Ha-1)", y = NULL,
       # fill = "Ocean",
       subtitle = "Saccharina latissima - Posterior predictions") +
  theme_clean() +
  theme(legend.position = "bottom")

# describing the full posterior distribution
Slat_estiamtes <- as.data.frame(describe_posterior(Slat.prod.final,centrality="mean"))
Slat_estiamtes$taxa <- c("Saccharina latissima")

Slat_estiamtes

write.csv(Slat_estiamtes,file = "outputs/Slat_C_prod_rate_estiamtes.csv")

```

```{r}

rm(list= ls()[!(ls() %in% c( "Aclath.prod.1", "Aclath.prod.2", "Aclath.prod.3","Aclath.prod.4", "Aclath_C_prod_df", "Alcath_c_prod_test_df",
                             "C_prod_model_data_sppsplit", "C_prod_rate_model_data", "C_Production_Collated_DF", 
                             "Ccost.prod.1","Ccost.prod.2","Ccost_C_prod_df", "Ccost_c_prod_test_df",
                             "LdigHnig.prod.1","LdigHnig.prod.2","LdigHnig.prod.3", "LdigHnig.prod.4", "LdigHnig_C_prod_df", "LdigHnig_c_prod_test_df", 
                             "Lsol.prod.1", "Lsol.prod.2","Lsol_C_prod_df", "Lsol_c_prod_test_df",
                             "Mpyr.prod.1","Mpyr.prod.2", "Mpyr_C_prod_df", "Mpyr_C_prod_test_df", 
                             "Nleu.prod.1","Nleu.prod.2", "Nleu_C_prod_df",             "Nleu_c_prod_test_df", 
                             "Pcal.prod.1", "Pcal_C_prod_df","Pcal_c_prod_test_df", 
                             "Pgar.prod.1", "Pgar.prod.2", "Pgar_C_prod_df", "Pgar_c_prod_test_df", 
                             "priors_FE", "priors_IO", 
                            "Slat.prod.4","Slat.prod.3", "Slat.prod.2", "Slat.prod.1", "Slat_C_prod_df", "Slat_c_prod_test_df"))])

save.image(file="Rdata/Carbon_Production_Rate_BRMs.RData")
```